[package]
build = "../build/build.rs"
name = "create-msg"
version = "0.1.0"
edition = "2018"

[dependencies]
base64 = "0.13.0"
clap = "3.0.0-beta.2"
hex = "0.4.2"
serde_json = "1.0.62"
tokio = { version = "0.2.13", features = ["macros"] }

ton_block = { git = "https://github.com/tonlabs/ton-labs-block.git" }
ton_client = { git = 'https://github.com/tonlabs/TON-SDK.git', package = "ton_client" }
ton_types = { git = "https://github.com/tonlabs/ton-labs-types.git" }
ton_vm = { git = "https://github.com/tonlabs/ton-labs-vm.git" }

ton_node_old = { path = "../ton_node" }

